language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

env:
    - USE_CYTHON=True
    - USE_CYTHON=False

install:
    - pip install coverage --use-mirrors
    - if [[ $USE_CYTHON == 'True' ]]; then
    -     pip install cython --use-mirrors
    -     python setup.py build_ext --inplace
    - fi
script:
    - nosetests --with-doctest
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then USE_CYTHON=False ; fi
    - python -c 'import multipledispatch ; assert multipledispatch.dispatcher.USE_CYTHON == '$USE_CYTHON

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install coveralls --use-mirrors ; coveralls ; fi

notifications:
  email: false
