language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"
    - "pypy"
    - "pypy3"

install:
    - pip install coverage
    - pip install --upgrade pytest pytest-benchmark

script:
    - |
      if [[ $(bc <<< "$TRAVIS_PYTHON_VERSION >= 3.3") -eq 1 ]]; then
         py.test --doctest-modules multipledispatch
      else
         py.test --doctest-modules --ignore=multipledispatch/tests/test_dispatcher_3only.py multipledispatch
      fi

after_success:
    - |
      if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install coveralls; coveralls ; fi

notifications:
  email: false
